### ISSUE TITLE
FIX RENDER -> app.js

### ISSUE THREAD

**Issue by Renurin** [unb-mds/2024-1-Squad08#14]
arrumar a renderização do app js que não está funcionando por algum motivo.

**Comment by RA-Salles** [comment]
Added myself as an assignee. Will begin works after merging database with main, which means very very soon.

**Comment by Renurin** [comment]
explaining briefly: the Browser Routers are not rendering the JSX for some weird reason =)

**Comment by Renurin** [comment]
IT WORKED !!!!! (still gotta fix the pages though)
